In [1]:
import dask
import dask.dataframe as df
import numpy as np
import pandas as pd
adultos = df.read_csv('../data/adult_ssn.csv')
np.random.seed(0)

In [2]:
np.random.seed(0)
loc, scale = 0., 1.
s = np.random.laplace(loc, scale, 10)
s

array([ 0.10272733,  0.56278358,  0.23007597,  0.09405397, -0.16568913,
        0.34501211, -0.13333207,  1.53037723,  2.621765  , -0.26542098])

In [3]:
r = np.random.laplace(loc, scale, 10)
r

array([ 0.87574896,  0.05952693,  0.14628567,  1.90510697, -1.95142049,
       -1.74721488, -3.20801514,  1.0943405 ,  0.81263705,  1.3471671 ])

In [4]:
r

array([ 0.87574896,  0.05952693,  0.14628567,  1.90510697, -1.95142049,
       -1.74721488, -3.20801514,  1.0943405 ,  0.81263705,  1.3471671 ])

In [6]:
pdf = pd.DataFrame({'x':[1,2,3,4],'y':[2,3,4,5],'z':[3,4,5,6]})
pdf

x  y  z
0  1  2  3
1  2  3  4
2  3  4  5
3  4  5  6

In [7]:
ddf = df.from_pandas(pdf, npartitions=2)
ddf

Dask DataFrame Structure:
                   x      y      z
npartitions=2                     
0              int64  int64  int64
2                ...    ...    ...
3                ...    ...    ...
Dask Name: from_pandas, 2 tasks

In [28]:
labels = ddf.astype(str)

In [29]:
print(labels)
labels.compute()

Dask DataFrame Structure:
                    x       y       z
npartitions=2                        
0              object  object  object
2                 ...     ...     ...
3                 ...     ...     ...
Dask Name: astype, 4 tasks


x  y  z
0  1  2  3
1  2  3  4
2  3  4  5
3  4  5  6

In [30]:
new_labels = labels.apply(lambda x: ' '.join(x.tolist()), axis=1, meta=('w', 'object'))

In [31]:
new_labels.compute()

0    1 2 3
1    2 3 4
2    3 4 5
3    4 5 6
Name: w, dtype: object

In [25]:
new_labels.columns

Index(['w'], dtype='object')

In [ ]:
labels.head()